global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'politika_bot'
    static_configs:
      - targets: ['172.17.0.1:8000']
    metrics_path: /metrics

  - job_name: 'economy_bot'
    static_configs:
      - targets: ['172.17.0.1:8001']
    metrics_path: /metrics

  - job_name: 'cinema_bot'
    static_configs:
      - targets: ['172.17.0.1:8002']
    metrics_path: /metrics

  - job_name: 'urgent_bot'
    static_configs:
      - targets: ['172.17.0.1:8005']
    metrics_path: /metrics
